# Generated by Django 5.2.7 on 2025-10-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocatecase',
            name='case_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='advocatecase',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='bar_council_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='specialization',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_type',
            field=models.CharField(blank=True, choices=[('TOTP', 'TOTP')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('advocate', 'Advocate'), ('admin', 'Admin')], db_index=True, max_length=20),
        ),
    ]
