# Generated by Django 5.2.7 on 2025-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateprofile',
            name='certificates',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
