# Generated by Django 5.2.7 on 2025-10-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_type',
            field=models.CharField(blank=True, choices=[('TOTP', 'TOTP'), ('EMAIL', 'EMAIL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('advocate', 'Advocate'), ('admin', 'Admin')], max_length=20),
        ),
    ]
