# Generated by Django 5.2.7 on 2025-10-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocatecase',
            name='advocate',
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddIndex(
            model_name='advocateprofile',
            index=models.Index(fields=['user'], name='advocate_pr_user_id_dadf44_idx'),
        ),
        migrations.AddIndex(
            model_name='advocateprofile',
            index=models.Index(fields=['specialization'], name='advocate_pr_special_91629e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='client_prof_user_id_980bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['phone_number'], name='client_prof_phone_n_844a60_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user'], name='otp_user_id_7cbb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code'], name='otp_code_23542d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AlterModelTable(
            name='advocateprofile',
            table='advocate_profile',
        ),
        migrations.AlterModelTable(
            name='clientprofile',
            table='client_profile',
        ),
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.DeleteModel(
            name='AdvocateCase',
        ),
    ]
