# Generated by Django 5.2.7 on 2025-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_advocateprofile_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
