# Generated by Django 5.2.7 on 2025-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mfa_enabled_user_mfa_secret_user_mfa_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
